// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzZCwxFoqCa8PouoFdzNm54HRbG2VKXHg',
    appId: '1:66007203323:web:dca478789b1c067797df5e',
    messagingSenderId: '66007203323',
    projectId: 'dearlog-fdca5',
    authDomain: 'dearlog-fdca5.firebaseapp.com',
    storageBucket: 'dearlog-fdca5.firebasestorage.app',
    measurementId: 'G-D40G4SQT1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU7Xz95N4uz8v91dcW6anhcsWmgEhTF2I',
    appId: '1:66007203323:android:03e2a908944cdbfa97df5e',
    messagingSenderId: '66007203323',
    projectId: 'dearlog-fdca5',
    storageBucket: 'dearlog-fdca5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQL8PYF0lxEvuxteOUxReo3YwbUgeDIko',
    appId: '1:66007203323:ios:6078bcff56fed9b897df5e',
    messagingSenderId: '66007203323',
    projectId: 'dearlog-fdca5',
    storageBucket: 'dearlog-fdca5.firebasestorage.app',
    iosBundleId: 'com.example.dearlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQL8PYF0lxEvuxteOUxReo3YwbUgeDIko',
    appId: '1:66007203323:ios:6078bcff56fed9b897df5e',
    messagingSenderId: '66007203323',
    projectId: 'dearlog-fdca5',
    storageBucket: 'dearlog-fdca5.firebasestorage.app',
    iosBundleId: 'com.example.dearlog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzZCwxFoqCa8PouoFdzNm54HRbG2VKXHg',
    appId: '1:66007203323:web:d984c85ef127f82d97df5e',
    messagingSenderId: '66007203323',
    projectId: 'dearlog-fdca5',
    authDomain: 'dearlog-fdca5.firebaseapp.com',
    storageBucket: 'dearlog-fdca5.firebasestorage.app',
    measurementId: 'G-JVNP85NCLT',
  );
}
